### ISSUE TITLE
angular testing structure folders.

### ISSUE THREAD

**Issue by ngnam** [tieppt/ng-ent-structure#1]
Hi anh, em đã xem qua repo trên a, e và nhiều bạn cũng đang quan tâm đean phần testing, a có thể chia một phần cũng như quy trình để triển khai phần testing cho những dự án Angular đã tồn tại và những dự án mới sẽ xây dựng sau này.

**Comment by tieppt** [comment]
component ở đâu spec file ở đó, angular cli đã gen sẵn thế rồi em
